project_name: twb-websocket
builds:
- env:
  - CGO_ENABLED=0
  goos:
    - linux
    - darwin
    # TODO: Enable windows support
    # Right now compilation on windows doesn't work
    # One idea would be to split the buzzer.go files
    # and enable only software support
    # See https://dave.cheney.net/2013/10/12/how-to-use-conditional-compilation-with-the-go-build-tool
    # - windows
  goarch:
    - 386
    - amd64
    - arm
    - arm64
archives:
  - name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    replacements:
      darwin: macOS
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
    format_overrides:
    - goos: windows
      format: zip
    files:
      - LICENSE
      - README.md
      - static/*
checksum:
  name_template: '{{ .ProjectName }}_checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
    - Merge pull request
    - Merge branch